### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by LonDat** [zawys/vscode-as-git-mergetool#3] opened 2020-11-25 00:25 UTC
## Steps to reproduce

Run command "Git mergetool: start git merge" from command list in VS Code.

It's file in conflict. The file in conflict start with   "xxx <?xml version="1.0" encoding="utf-8"?>".
Hint: file is encoded in UTF8 with BOM (not sure, if matters).

This is error showed in console:

  xxx <?xml version="1.0" encoding="utf-8"?>

       ^
SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:942:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)   
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11

## Environment

- Version of the extension: 0.10.0
- Operating system: Win10
- VSCode ver: 1.51.0

**Comment by zawys** [comment] 2020-11-25 10:23
Hi! Thanks for reaching out.

However, I cannot reproduce this. I created a test repository with a conflicting file with a file name `xxx .txt` with BOM but that went without exceptions.

Please provide a minimal example (e.g. zipped repository) and which other extensions you use. Closing this until you provide further information.

**Closed as completed by zawys** 2020-11-25 10:23 UTC
Labels: bug
